### ISSUE TITLE
Error on first use

### ISSUE THREAD

**Issue by MarkAPitt** [mim/auditoryBubbles#3]
A file loads fine, but when I left-click on the spectrogram, the following error code is generated.
The file plays fine, and I can change Plotting values and the spectrogram is updated without a problem. 
Am I not using it correctly?

---

Attempt to reference field of non-structure array.

Error in bubbleEditor>mainAxes_ButtonDownFcn (line 377)
handles.bubbleT_s(end+1) = eventdata.IntersectionPoint(1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in bubbleEditor (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)bubbleEditor('mainAxes_ButtonDownFcn',hObject,eventdata,guidata(hObject))

**Comment by mim** [comment]
Hmm... that might be because we're using different versions of matlab.  What version are you using?  I'm on 2015a.  Could you set a breakpoint at that line (377 in bubbleEditor.m) and post here what is in the "eventdata" variable?

**Comment by MarkAPitt** [comment]
eventdata is empty.
I am running 2014a. Let me know if you want me to upgrade, and I can do so sometime this week.

**Comment by mim** [comment]
Yeah, try it with the new version. I'll see if I can modify it to get it
running on an older version as well.

**Comment by MarkAPitt** [comment]
I upgraded to 2015b, the latest OSU provides.
wavread()/wavwrite() are no longer supported, so I had to make a few changes to my copy. I am having trouble with the Github GUI interface, so I did not do the obvious and create a branch and a pull request. Sorry.

File editing now works, but saving is causing the following error and not saving the file, named "test." I did not troubleshoot further.

<i>Problem writing C:\Users\pitt\Desktop\auditoryBubbles-master\test
  The value of 'filename' is invalid. Expected input to be one of these types:

char

Instead its type was double. .. </i>

**Comment by mim** [comment]
I've just pushed updates to the auditoryBubbles repo and the mimLib repo that replace `wavread`/`wavwrite` with `audioread`/`audiowrite`.  Give those a shot if you can.  

If not, you can replace `wavwrite` with `audiowrite`, but note that the order of the arguments is different (which is probably what's causing this problem):

``` matlab
wavwrite(y, fs, outFile)
audiowrite(outFile, y, fs)
```

**Comment by MarkAPitt** [comment]
Thank you. All is well. I would never have thought they would change the order of the parameters.
